### ISSUE TITLE
Use a module to export components to avoid import statements in component files

### ISSUE THREAD

**Issue by msd96drexel** [cci-toast/frontend#126]
In Angular, you can create a module for your components which imports the components and exports them. Then you can use the declare module in your app. When you do this, you don't have to import components into other components to use them. This would be really awesome to have, but I've been researching and haven't found a React equivalent of this. ... but we can't give up!! :)

Angular module resources:
https://angular.io/guide/architecture-modules
https://angular.io/guide/ngmodules

**Comment by pinkdragon1000** [comment]
This may be sort of what you're looking for: https://rollupjs.org/guide/en/
